name: Bump version and test build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Bump version
      run: mvn versions:set -DnextSnapshot=true

    - name: Add & Commit version
      uses: EndBug/add-and-commit@v4.2.1
      with:
        author_name: HHU - BOT
        message: "Update version"
        add: "pom.xml"
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop # Shutdown the Default MySQL

    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: ${{ secrets.db_name }}
        mysql user: ${{ secrets.db_login }}
        mysql password: ${{ secrets.db_password }}

    - name: Build with Maven
      run: mvn -B test --file pom.xml "-Ddatasource.url=${{ secrets.datasource_url }}" "-Ddatasource.username=${{ secrets.db_login }}" "-Ddatasource.password=${{ secrets.db_password }}" "-Dmail.host=${{ secrets.mail_host }}" "-Dmail.username=${{ secrets.mail_username }}" "-Dmail.password=${{ secrets.mail_password }}"

#    - name: Deploy to Wildfly
#      run: mvn wildfly:deploy "-DwfHost=${{ secrets.wildfly_hostname }}" "-DwfPort=${{ secrets.wildfly_port }}" "-DwfUsername=${{ secrets.wildfly_username }}" "-DwfPassword=${{ secrets.wildfly_password }}"

