name: On push master deploy to Wildfly

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      #      - uses: actions/checkout@v1
      #      - name: Bump version
      #        run: mvn build-helper:parse-version versions:set -DnewVersion=${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.nextIncrementalVersion} versions:commit
      #
      #      - uses: actions/checkout@master
      #      - name: Create local changes
      #        run: |
      #          - name: Commit files
      #            run: |
      #              git config --local user.email "action@github.com"
      #              git config --local user.name "GitHub Action"
      #              git commit -m "Bump version" -a
      #          - name: Push changes
      #            uses: ad-m/github-push-action@master
      #            with:
      #              github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop # Shutdown the Default MySQL

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: ${{ secrets.db_name }}
          mysql user: ${{ secrets.db_login }}
          mysql password: ${{ secrets.db_password }}

      - name: Build with Maven
        run: mvn -B test --file pom.xml

      - name: Deploy to Wildfly
        run: mvn wildfly:deploy "-Dwfhost=${{ secrets.wildfly_hostname }}" "-Dwfport=${{ secrets.wildfly_port }}" "-Dwfusername=${{ secrets.wildfly_username }}" "-Dwfpassword=${{ secrets.wildfly_password }}"